log_format realipformat '$http_cf_connecting_ip($http_cf_ipcountry) [$time_local] $request_method($status):$request_uri REFERER:$http_referer USER_AGENT:$http_user_agent';
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Host $host;

server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.php index.html index.htm;
    server_name coding.tools;
    client_max_body_size 64M;
    access_log /var/log/nginx/coding.log realipformat;

    location / {
        proxy_pass http://127.0.0.1:8080;
    }

}

server {
    listen 80;
    listen [::]:80;
    root /tmp/codingtool;
    server_name download.coding.tools;
    client_max_body_size 64M;
    expires off;
    add_header Content-Disposition 'attachment;';
}

server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.php index.html index.htm;
    server_name photo2pixel.co;
    access_log /var/log/nginx/photo2pixel.log realipformat;

    location / {
        proxy_pass http://127.0.0.1:8090;
    }

}

server {
    listen 80 default_server;
    access_log /var/log/nginx/malicious.log;
    return 404;
}