const examples = {
  "base64-encode": { input: "Hello from Coding.Tools MCP" },
  "base64-decode": { input: "SGVsbG8gZnJvbSBDb2RpbmcuVG9vbHMgTUNQ" },
  "md5-generator": { input: "release-notes-v1" },
  "sha1-generator": { input: "release-notes-v1" },
  "sha256-generator": { input: "release-notes-v1" },
  "sha384-generator": { input: "release-notes-v1" },
  "sha512-generator": { input: "release-notes-v1" },
  "password-generator": { options: { length: 20, symbols: true } },
  "hex-to-decimal": { input: "0x1A3F" },
  "decimal-to-hex": { input: "6719" },
  "octal-to-decimal": { input: "755" },
  "decimal-to-octal": { input: "493" },
  "binary-to-decimal": { input: "11010110" },
  "decimal-to-binary": { input: "214" },
  "binary-to-hex": { input: "111100001010" },
  "hex-to-binary": { input: "F0A" },
  "ascii-table": {},
  "hex-to-ascii": { input: "53 74 61 74 75 73 3A 20 4F 4B" },
  "ascii-to-hex": { input: "Status: OK" },
  "binary-to-text": { input: "01001100 01101111 01100111 00100000 01001111 01001011" },
  "text-to-binary": { input: "Log OK" },
  "fraction-to-decimal": { input: "7/8" },
  "decimal-to-fraction": { input: "0.125" },
  "percent-to-decimal": { input: "18.5%" },
  "decimal-to-percent": { input: "0.185" },
  "percent-to-fraction": { input: "12.5%" },
  "fraction-to-percent": { input: "1/8" },
  "hex-to-rgb": { input: "#3366CC" },
  "rgb-to-hex": { input: { r: 51, g: 102, b: 204 } },
  "hex-to-rgba": { input: "#3366CC", options: { alpha: 0.65 } },
  "rgba-to-hex": { input: { r: 51, g: 102, b: 204, a: 0.65 } },
  "roman-numerals-chart": {},
  "roman-numerals-to-numbers": { input: "MMXXVI" },
  "numbers-to-roman-numerals": { input: "2026" },
  "text-editor": { input: "Release notes\n- Fix login\n- Add MCP endpoint" },
  "regex-tester": {
    input: "Order #A102 total $58.40",
    options: { pattern: "#[A-Z]\\d+", flags: "g" }
  },
  "regex-replace": {
    input: "Ticket ABC-123 is ready for review",
    options: { pattern: "[A-Z]{3}-\\d{3}", replacement: "[ticket-id]", flags: "g" }
  },
  "url-encode": { input: "hello world & tea=green", options: { mode: "component", spaceAsPlus: false } },
  "url-decode": { input: "https://example.com/search?q=hello+world&redirect=https%3A%2F%2Fcoding.tools%2F", options: { parseQuery: true } },
  "text-compare": { input: "status: draft\nowner: alice", options: { compareTo: "status: published\nowner: alice" } },
  "word-counter": { input: "Ship the MCP endpoint today.\nAdd examples for every tool." },
  "character-count": { input: "MCP endpoint is ready for tool automation." },
  "case-converter": { input: "quarterly revenue report", options: { mode: "title" } },
  "reverse-text": { input: "stressed" },
  "number-to-words": { input: "12345" },
  "json-formatter": { input: "{\"name\":\"Coding.Tools\",\"features\":[\"MCP\",\"A2A\"]}", options: { spaces: 2 } },
  "json-diff": { input: "{\"user\":{\"name\":\"Alice\",\"role\":\"admin\"}}", options: { compareTo: "{\"user\":{\"name\":\"Alice\",\"role\":\"editor\"}}" } },
  "json-minifier": { input: "{\n  \"name\": \"Coding.Tools\",\n  \"features\": [\"MCP\", \"A2A\"]\n}" },
  "xml-formatter": { input: "<invoice><id>1001</id><total>58.40</total></invoice>" },
  "xml-minifier": { input: "<invoice>\n  <id>1001</id>\n  <total>58.40</total>\n</invoice>" },
  "json-to-xml": { input: "{\"invoice\":{\"id\":1001,\"total\":58.4}}", options: { rootName: "document" } },
  "xml-to-json": { input: "<invoice><id>1001</id><total>58.40</total></invoice>" },
  "html-beautifier": { input: "<section><h1>Docs</h1><p>MCP ready</p></section>" },
  "html-minifier": { input: "<section>\n  <h1>Docs</h1>\n  <p>MCP ready</p>\n</section>" },
  "javascript-beautifier": { input: "function total(items){return items.reduce((sum,item)=>sum+item.price,0);}" },
  "javascript-minifier": { input: "function total(items) { return items.reduce((sum, item) => sum + item.price, 0); }" },
  "css-beautifier": { input: ".button{color:white;background:#3366cc;padding:8px 12px;}" },
  "css-minifier": { input: ".button {\n  color: white;\n  background: #3366cc;\n  padding: 8px 12px;\n}" },
  "sql-formatter": { input: "select id,total from invoices where paid = 1 order by total desc" },
  "sql-minifier": { input: "select id, total\nfrom invoices\nwhere paid = 1\norder by total desc" },
  "photo2pixel": {},
  "image-resize": {},
  "image-crop": {},
  "compress-png": {},
  "compress-jpeg": {},
  "progressive-jpeg": {},
  "image-to-base64": { input: { url: "https://coding.tools/assets/img/photo2pixel-demo.png" } },
  "exif-viewer": {},
  "exif-remover": {}
};

module.exports = {
  arguments: examples,
  argumentsJson: Object.fromEntries(
    Object.entries(examples).map(([toolId, value]) => [toolId, JSON.stringify(value)])
  )
};
