import os
import time

FLAG_IS_PRODUCTION_ENV = not (os.name == 'nt')
YEAR = str(time.localtime().tm_year)
LOG_FILE_PATH = '/app/log/daily.log'

# Version
CSS_VERSION_UNIT = '20210710.1'
CSS_VERSION_FONTAWESOME = '6.1.1'
CDNJS_VERSION_JQUERY = '3.5.1'
CDNJS_VERSION_BOOTSTRAP = '5.1.3'
CDNJS_VERSION_CODEMIRROR = '5.65.4'
CDNJS_VERSION_CRYPTO_JS = '4.1.1'
CDNJS_VERSION_JS_BEAUTIFY = '1.14.0'
CDNJS_VERSION_HTML_MINIFIER = '4.0.0'
CDNJS_VERSION_JXON = '1.6.1'
CDNJS_VERSION_BIGNUMBER = '9.0.2'
CDNJS_VERSION_COOKIE_CONSENT = '3.1.1'
CDNJS_VERSION_FileSaver = '2.0.5'
CDNJS_VERSION_DropZone = '5.9.3'

# Color
# MAIN_COLOR = '#2f8d59'
MAIN_COLOR = '#309d5a'

# IP2LOCATION
IP2LOCATION_DATABASE_PATH = '/app/IP2Location/ip_4_20210626.db'
# IP2LOCATION_DATABASE_PATH = '/app/IP2Location/ip_4_20210626.db'
# IP2LOCATION_DATABASE_PATH = '/app/IP2Location/IP2Location.db'
# IP2LOCATION_SQLITE_PATH = 'sqlite:////app/IP2Location/IP2Location.db'
IP2LOCATION_IPV4_CSV_PATH = '/app/IP2Location/IP2LOCATION-LITE-DB11.CSV'
# IP2LOCATION_IPV6_CSV_PATH = '/app/IP2Location/IP2LOCATION-LITE-DB11.IPV6.CSV'


UPLOAD_TEMP_FOLDER_PATH = '/tmp/codingtool'
UPLOAD_TEMP_FOLDER_CLEAR_CACHE_INTERVAL_IN_MINUTES = 30
DOWNLOAD_URL_PREFIX = 'https://downloadv2.coding.tools/'